# Generated by Django 5.1.4 on 2024-12-05 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0002_remove_student_course_remove_student_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='enrollment_date',
        ),
    ]
